# Generated by Django 3.2.11 on 2022-02-25 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_commentarticle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='master',
            new_name='user',
        ),
    ]
