# Generated by Django 3.2.11 on 2022-02-26 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20220225_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='master',
            new_name='user',
        ),
    ]
