# Generated by Django 3.2.11 on 2022-02-25 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkWithUs',
        ),
    ]
